site_name: Documentation Name
repo_url: https://github.com/example/repository/
edit_uri: edit/main/docs/
repo_name: example/repository/
site_description: NeSI Support Documentation
site_dir: public
site_url: https://docs.nesi.org.nz/
theme:
  name: material
  custom_dir: overrides
  favicon: assets/icons/favicon_nesi.ico
  language: en
  logo: assets/icons/logo_nesi.svg
  palette:
    - primary: custom
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - primary: custom
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.path
    - content.code.copy
    - content.action.edit
    - header.site_name_homepage
hooks:
  - mkdocs_hooks.py
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - toc:
      baselevel: 1
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets: null
extra:
  analytics:
    provider: google
    property: <insert tracking code here>
plugins:
  - search
  - open-in-new-tab
  - redirects:
      map_file: redirect_map.yml
  - awesome-pages:
      filename: .pages.yml
  - tags:
      tags: false
  - git-revision-date-localized:
      enable_creation_date: false
  - macros:
      include_dir: overrides
      module_name: macro_hooks
      on_error_fail: true
      verbose: false
extra_css:
  - assets/stylesheets/theme.css
extra_javascript:
  - assets/javascripts/general.js
  # Uncomment to include nesi status window.
  # - https://status.nesi.org.nz/embed/script.js
